name: CICDwork
on:
  pull_request:
    branches: [ Development ]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!	
  DeployDevelopment:
    name: Deploy to Dev 
    if: github.base_ref == 'Development'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Development
    steps:
     - name: Deploy
       uses: actions/github -script@0.2.0
       with:
         script: |
           github.pullRequests.merge({
             owner: context.payload.repository.owner.login,
             repo: context.payload.repository.name,
             pull_number: context.payload.pull_request.number
           })
            
          
 

