name: CICDwork
on:
  push:
    branches: [ San20091991-patch-1  ]
  pull_request:
    branches: [ San20091991-patch-1  ]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!	
  DeployDevelopment:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: San20091991-patch-1
          target_branch: Development
          github_token: ${{ secrets.GITHUB_TOKEN }}
     
          
          
 

