name: CICDwork
on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!	
  DeployDevelopment:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Development
    steps:
     - name: Deploy
       run: echo I am deploying!! 
  DeployStaging:
    name: Deploy to Staging 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Staging
    steps:
     - name: Deploy
       run: echo I am deploying! 
  DeployProduction:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: Production 
    steps:
     - name: Deploy
       run: echo I am deploying!

